Completed first task
keda-vlad/bookstore pull request #1
Opened 2023-08-31 19:48 UTC by keda-vlad

2023-09-01 16:11 UTC, Denis-Balako requested changes
Good solution! Let's improve it 😄

2023-09-01 16:11 UTC, Denis-Balako commented on src/main/java/mate/academy/bookstore/BookstoreApplication.java
> +    private BookService bookService;
Don't forget about dependency injection - provide this service through constructor and add @ Autowired above constructor.

2023-09-01 16:11 UTC, Denis-Balako commented on src/main/java/mate/academy/bookstore/model/Book.java
> +    private String coverImage;
https://medium.com/@centizennationwide/mysql-naming-conventions-e3a6f6219efe
```suggestion
    @Column(name = "cover_image")
    private String coverImage;
```

2023-09-01 16:11 UTC, Denis-Balako commented on src/main/java/mate/academy/bookstore/service/BookServiceImpl.java
> +    private BookRepository bookRepository;
Same as in BookstoreApplication about DI

2023-09-01 19:09 UTC, Denis-Balako approved these changes
LGTM!

2023-09-08 06:26 UTC, boroda4436 approved these changes

2023-09-09 21:26 UTC, merged