Spring order
keda-vlad/bookstore pull request #11
Opened 2023-09-20 19:17 UTC by keda-vlad

2023-09-22 15:23 UTC, vovasalyha requested changes
GJ. Let's improve it a bit

2023-09-22 15:23 UTC, vovasalyha commented on src/main/java/mate/academy/bookstore/service/impl/OrderServiceImpl.java
> +    @Override
```suggestion
    @Transactional
    @Override
```
What if your method fails in the middle of execution? Do not forget about transactions

2023-09-22 15:23 UTC, vovasalyha commented on src/main/java/mate/academy/bookstore/service/impl/OrderServiceImpl.java
> +    public OrderDto placeAnOrder(Long userId, PlaceAnOrderDto placeAnOrderDto) {
Is it possible to reduce complexity of this method? maybe extract some logical parts into private methods

2023-09-22 15:23 UTC, vovasalyha commented on src/main/java/mate/academy/bookstore/service/impl/OrderServiceImpl.java
> +        Order order = orderRepository.findById(id).orElseThrow(() ->
What if user will specify id of an order which do not belong to him? You should validate not only access to the particular endpoint, but also access of a user to the particular resource (make sure that in other methods and services you don't forget about it)

2023-09-22 15:23 UTC, vovasalyha commented on src/main/resources/db/changelog/changes/12-create-order-table.yaml
> +              - column:
add FK

2023-09-22 15:23 UTC, vovasalyha commented on src/main/resources/db/changelog/changes/13-create-order-item-table.yaml
> +                  name: book_id
add FK

2023-09-25 12:50 UTC, andrii-hoienko requested changes
GJ, I left minor comments

2023-09-25 12:50 UTC, andrii-hoienko commented on src/main/java/mate/academy/bookstore/service/impl/OrderServiceImpl.java
> +    private Order buildOrder(
JFUI: Word build is often associated with pattern builder, buildOrder for me means that you are building order, not creating it. In this particular case it does not matter, but it is still confusing

2023-09-25 12:50 UTC, andrii-hoienko commented on src/main/java/mate/academy/bookstore/service/impl/OrderServiceImpl.java
> +    public OrderDto placeAnOrder(Long userId, PlaceAnOrderDto placeAnOrderDto) {
Think about what else methods should be transactional

2023-09-25 12:50 UTC, andrii-hoienko commented on src/main/resources/db/changelog/changes/15-add-foreign-keys.yaml
> +            referencedColumnNames: id
Add empty line

2023-09-25 12:50 UTC, andrii-hoienko commented on src/main/resources/db/changelog/changes/13-create-order-item-table.yaml
> +                  name: book_id
not resolved

2023-09-25 12:55 UTC, keda-vlad commented on src/main/resources/db/changelog/changes/13-create-order-item-table.yaml
> +                  name: book_id
Added in 15-add-foreign-keys.yaml

2023-09-25 15:51 UTC, vovasalyha approved these changes
approving, but resolve merge conflicts

2023-09-26 03:25 UTC, merged