Spring test book
keda-vlad/bookstore pull request #12
Opened 2023-09-28 11:21 UTC by keda-vlad

2023-09-28 15:33 UTC, DmytroV95 approved these changes
LGTM!

2023-09-28 15:33 UTC, DmytroV95 commented on src/test/java/mate/academy/bookstore/config/CustomMySqlContainer.java
> +        System.setProperty("TEST_DB_PASSWORD", mySqlContainer.getPassword());
You can do it constants.

2023-10-03 14:18 UTC, andrii-hoienko requested changes
Gj! But still some improvements required

2023-10-03 14:18 UTC, andrii-hoienko commented on src/test/java/mate/academy/bookstore/controller/BookControllerTest.java
> +        Assertions.assertEquals(expected.size(), actual.length);
Please use static import

2023-10-03 14:18 UTC, andrii-hoienko commented on src/test/java/mate/academy/bookstore/controller/BookControllerTest.java
> +        //return update
remove comments

2023-10-03 14:18 UTC, andrii-hoienko commented on src/test/java/mate/academy/bookstore/controller/CategoryControllerTest.java
> +    static void afterAll(
should be on top of the class

2023-10-03 14:18 UTC, andrii-hoienko commented on src/test/java/mate/academy/bookstore/controller/CategoryControllerTest.java
> +    void update_ValidRequestDto_ReturnBookDto() throws Exception {
Tests looks like a mess, please separate on 3 blocks: 1. precondition 2. action 3. assertion

2023-10-03 14:18 UTC, andrii-hoienko commented on src/test/java/mate/academy/bookstore/controller/CategoryControllerTest.java
> +        MvcResult result = mockMvc.perform(
Please try to avoid 2 'mockMvc.perform' in one test

2023-10-03 14:18 UTC, andrii-hoienko commented on src/test/java/mate/academy/bookstore/controller/CategoryControllerTest.java
> +        List<BookDtoWithoutCategoryIds> expected = List.of(
Please try to use constants and reuse them, do not create precondition different foeach test

2023-10-03 14:18 UTC, andrii-hoienko commented on src/test/java/mate/academy/bookstore/repository/book/BookRepositoryTest.java
> +        Assertions.assertEquals("The Hobbit", actual.get().getTitle());
Please make sure that book is equal to expected one, not just a title (check all tests)

2023-10-03 14:18 UTC, andrii-hoienko commented on src/test/java/mate/academy/bookstore/repository/category/CategoryRepositoryTest.java
> +        Assertions.assertEquals(2, actual.size());
code duplication

2023-10-03 14:18 UTC, andrii-hoienko commented on src/test/java/mate/academy/bookstore/repository/category/CategoryRepositoryTest.java
> +        actual = actual.stream()
what is the reason of doing operations with actual result?

2023-10-03 14:18 UTC, andrii-hoienko commented on src/test/java/mate/academy/bookstore/service/impl/BookServiceImplTest.java
> +        Mockito.verify(bookMapper, Mockito.times(1)).toModel(Mockito.any());
times(1) is by default

2023-10-03 14:18 UTC, andrii-hoienko commented on src/test/java/mate/academy/bookstore/service/impl/BookServiceImplTest.java
> +        Mockito.verify(bookMapper, Mockito.times(1)).toModel(Mockito.any());
It is not necessary to verify call of mocks when they defined in WHEN

2023-10-23 12:19 UTC, andrii-hoienko approved these changes
GJ!

2023-10-23 12:23 UTC, merged