Spring test shopping cart and order
keda-vlad/bookstore pull request #13
Opened 2023-10-02 02:30 UTC by keda-vlad

2023-10-09 11:20 UTC, Zel1oy approved these changes
Awesome

2023-10-17 11:41 UTC, andrii-hoienko requested changes
GJ! Let`s improve your solution

2023-10-17 11:41 UTC, andrii-hoienko commented on src/test/java/mate/academy/bookstore/controller/AuthenticationControllerTest.java
> +        System.out.println(actual);
What is the reason of println?

2023-10-17 11:41 UTC, andrii-hoienko commented on src/test/java/mate/academy/bookstore/controller/AuthenticationControllerTest.java
> +        Assertions.assertNotNull(actual);
Please use static import

2023-10-17 11:41 UTC, andrii-hoienko commented on src/test/java/mate/academy/bookstore/controller/OrderControllerTest.java
> +        OrderDto expected = new OrderDto(
Code duplication. To remove creation of same test data I suggest to create constants for common data or create method or even separate class to for such purpose

2023-10-17 11:41 UTC, andrii-hoienko commented on src/test/java/mate/academy/bookstore/controller/ShoppingCartControllerTest.java
> +    private Authentication authentication() {
Code duplication

2023-10-17 11:41 UTC, andrii-hoienko commented on src/test/java/mate/academy/bookstore/repository/order/OrderRepositoryTest.java
> +        Order order = new Order()
```suggestion
        Order expectedOrder = new Order()
```

2023-10-17 11:41 UTC, andrii-hoienko commented on src/test/java/mate/academy/bookstore/repository/order/OrderRepositoryTest.java
> +                .setId(1L)
It is difficult to read test when there are such huge order. To improve readability I suggest to move creation of order is separate method. In this case test will contain only 4 lines of code and will be significantly more readable

2023-10-17 11:41 UTC, andrii-hoienko commented on src/test/java/mate/academy/bookstore/repository/shoppingcart/ShoppingCartRepositoryTest.java
> +        System.out.println(expected.getCartItems());
reason of pringln?

2023-10-17 11:41 UTC, andrii-hoienko commented on src/test/java/mate/academy/bookstore/repository/shoppingcart/ShoppingCartRepositoryTest.java
> +        System.out.println(expected.getCartItems());
Is it possible to divide test into 3 logical parts (precondition, action and assertion) by white spaces?

2023-10-17 11:41 UTC, andrii-hoienko commented on src/test/java/mate/academy/bookstore/service/impl/CartItemServiceImplTest.java
> +        //Given
Please remove unnecessary comments, or if you want to mark parts of the test add such comments in each test

2023-10-17 11:41 UTC, andrii-hoienko commented on src/test/java/mate/academy/bookstore/service/impl/CartItemServiceImplTest.java
> +        Mockito.verify(cartItemMapper, Mockito.times(1)).toDto(Mockito.any());
times(1) is by default

2023-10-17 11:41 UTC, andrii-hoienko commented on src/test/java/mate/academy/bookstore/service/impl/CartItemServiceImplTest.java
> +        Mockito.verify(cartItemRepository, Mockito.times(1)).save(Mockito.any());
maybe it makes sence to check what exactly method 'save' saves instead of just 'any()'

2023-10-17 11:41 UTC, andrii-hoienko commented on src/test/java/mate/academy/bookstore/service/impl/OrderItemServiceImplTest.java
> +        Mockito.when(orderItemRepository.findAllByUserIdAndOrderId(
static import on when, verify, any etc

2023-10-23 14:37 UTC, vovasalyha approved these changes

2023-10-23 14:37 UTC, vovasalyha commented on src/test/java/mate/academy/bookstore/service/impl/CartItemServiceImplTest.java
> +        verify(cartItemRepository).save(any());
it's redundant to verify that stubbed method was called (you can check it in the method's documentation)

2023-10-24 07:28 UTC, merged