Spring web solution
keda-vlad/bookstore pull request #2
Opened 2023-09-04 18:10 UTC by keda-vlad

2023-09-04 20:44 UTC, JeniaSan commented on src/main/java/mate/academy/bookstore/BookstoreApplication.java
please read task description, you have to remove this bean, because you don't need to do something in main

2023-09-04 20:48 UTC, JeniaSan requested changes
Good job, only one minor mistake

2023-09-04 20:50 UTC, JeniaSan commented on src/main/java/mate/academy/bookstore/BookstoreApplication.java
I mean CommandLineRunner bean

2023-09-05 12:08 UTC, JeniaSan approved these changes
Good job

2023-09-08 14:09 UTC, vovasalyha approved these changes
GJ

2023-09-08 14:09 UTC, vovasalyha commented on src/main/java/mate/academy/bookstore/BookstoreApplication.java
>      private final BookService bookService;
you don't need this dependency anymore

2023-09-09 21:27 UTC, merged