added docker
keda-vlad/bookstore pull request #7
Opened 2023-09-13 19:53 UTC by keda-vlad

2023-09-15 15:27 UTC, vovasalyha requested changes
Good, but let's improve it a bit

2023-09-15 15:27 UTC, vovasalyha commented on Dockerfile
> +EXPOSE 8080
empty line

2023-09-15 15:27 UTC, vovasalyha commented on docker-compose.yaml
> +services:
add also service to run the backend app from the Dockerfile

2023-09-15 15:27 UTC, vovasalyha commented on .env
> +MYSQL_DATABASE=book_store
empty line

2023-09-15 15:27 UTC, vovasalyha commented on .gitignore
> +.env
It's OK to push .env file to git so others can test your project easily

2023-09-15 15:27 UTC, vovasalyha commented on pom.xml
> +            <groupId>org.postgresql</groupId>
Where do you use this driver?

2023-09-26 08:31 UTC, nacenik requested changes
Fix pr history. You have a lot of changes that are not related to the task.

2023-09-26 08:31 UTC, nacenik commented on docker-compose.yaml
> +      JAVA_TOOL_OPTIONS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:$DEBUG_PORT
add empty line

2023-09-26 12:11 UTC, Vasul-Pankiv approved these changes

2023-09-26 13:43 UTC, merged