Spring category
keda-vlad/bookstore pull request #8
Opened 2023-09-13 23:41 UTC by keda-vlad

2023-09-14 19:23 UTC, DmytroV95 requested changes
Good job! Left some comments to improve your solution.

2023-09-14 19:23 UTC, DmytroV95 commented on src/main/java/mate/academy/bookstore/controller/CategoryController.java
> +    //@PreAuthorize("hasRole('ROLE_ADMIN')")
You need to uncomment it to ensure admin-only access to create a category.

2023-09-14 19:23 UTC, DmytroV95 commented on src/main/resources/db/changelog/changes/07-create-categories-table.yaml
> +                    nullable: false
No empty line.

2023-09-14 19:23 UTC, DmytroV95 commented on src/main/resources/db/changelog/changes/08-create-book-category-table.yaml
> +                    nullable: false
No empty line.

2023-09-14 19:23 UTC, DmytroV95 commented on src/main/resources/db/changelog/changes/09-add-description-to-category.yaml
> +                  type: varchar(255)
No empty line.

2023-09-14 19:23 UTC, DmytroV95 commented on src/main/resources/db/changelog/db.changelog-master.yaml
> +      file: db/changelog/changes/09-add-description-to-category.yaml
No empty line.

2023-09-14 20:43 UTC, DmytroV95 approved these changes
LGTM. GJ!

2023-09-22 14:18 UTC, vovasalyha approved these changes
Approving, but add foreign key constraints

2023-09-22 14:18 UTC, vovasalyha commented on src/main/resources/db/changelog/changes/08-create-book-category-table.yaml
> +      changes:
add foreign key constraints

2023-09-23 22:49 UTC, merged